#ifndef _EF_SYSTEM_STATES_CFG_H_
#define _EF_SYSTEM_STATES_CFG_H_

enum {
  WELCOME_STATE,
  ENTER_CARD_STATE,
  CHECK_CARD_STATE,
  SELECTION_STATE,
  ENTER_PASSWORD_STATE,
  CHECK_PASSWORD,
  CHANGE_BALANCE_STATE,
  CONFIRM_BALANCE_STATE,
  UPDATED_BALANCE_STATE,
  READ_BALANCE_STATE,
  CHARGE_HISTORY_STATE
};

enum {
    PRINT_SELECTION_MENU,
    GET_KEYPAD_MENU
};

enum {
    PRINT_READ_BALANCE,
    READ_RFID_STATE,
    WAIT_KEYPAD_STATE
};

enum {
    PRINT_ENTER_BALANCE,
    ADD_BALANCE_KEYPAD
};

enum {
    CONFIRM_PRINT_STATE,
    CONFIRM_GET_KEYPAD_STATE
};

enum {
    PRINT_HISTORY_STATE,
    WAIT_PRESSED_STATE
};
#endif
